[AllowList]
  Files = []
Paths = []
Regexes = ["TokenSet;s\\.node\\.edges\\[\"\\*\"\\]=u\\}if\\(0==s\\.str\\.length&&\\(u\\.final=!0\\),n\\.push\\(\\{node:u,editsRemaining:s\\.editsRemaining-1,str:s\\.str\\}\\),1<"]
